package ca.sheridancollege.billana.domain;

public enum CarModel {

	ACCORD(CarMake.HONDA), CIVIC(CarMake.HONDA), CR_V(CarMake.HONDA), PILOT(CarMake.HONDA), ODYSSEY(CarMake.HONDA),
	RIDGELINE(CarMake.HONDA), INSIGHT(CarMake.HONDA), CLARITY(CarMake.HONDA), FIT(CarMake.HONDA), HR_V(CarMake.HONDA),
	PASSPORT(CarMake.HONDA), ELEMENT(CarMake.HONDA), S2000(CarMake.HONDA), NSX(CarMake.HONDA), COROLLA(CarMake.TOYOTA),
	CAMRY(CarMake.TOYOTA), AVALON(CarMake.TOYOTA), YARIS(CarMake.TOYOTA), PRIUS(CarMake.TOYOTA), RAV4(CarMake.TOYOTA),
	HIGHLANDER(CarMake.TOYOTA), FOUR_RUNNER(CarMake.TOYOTA), TACOMA(CarMake.TOYOTA), TUNDRA(CarMake.TOYOTA),
	SEQUOIA(CarMake.TOYOTA), SIENNA(CarMake.TOYOTA), SUPRA(CarMake.TOYOTA), LAND_CRUISER(CarMake.TOYOTA),
	MUSTANG(CarMake.FORD), FOCUS(CarMake.FORD), F_150(CarMake.FORD), ESCAPE(CarMake.FORD), EDGE(CarMake.FORD),
	EXPLORER(CarMake.FORD), TAURUS(CarMake.FORD), FUSION(CarMake.FORD), ECOSPORT(CarMake.FORD),
	TRANSIT_CONNECT(CarMake.FORD), RANGER(CarMake.FORD), TRANSIT(CarMake.FORD), SUPER_DUTY(CarMake.FORD),
	GT(CarMake.FORD), BRONCO(CarMake.FORD), BRONCO_SPORT(CarMake.FORD), MAVERICK(CarMake.FORD),
	SPARK(CarMake.CHEVROLET), SONIC(CarMake.CHEVROLET), CRUZE(CarMake.CHEVROLET), MALIBU(CarMake.CHEVROLET),
	IMPALA(CarMake.CHEVROLET), CAMARO(CarMake.CHEVROLET), CORVETTE(CarMake.CHEVROLET), TRAX(CarMake.CHEVROLET),
	EQUINOX(CarMake.CHEVROLET), BLAZER(CarMake.CHEVROLET), TRAVERSE(CarMake.CHEVROLET), TAHOE(CarMake.CHEVROLET),
	SUBURBAN(CarMake.CHEVROLET), COLORADO(CarMake.CHEVROLET), SILVERADO(CarMake.CHEVROLET), ALTIMA(CarMake.NISSAN),
	MAXIMA(CarMake.NISSAN), SENTRA(CarMake.NISSAN), VERSA(CarMake.NISSAN), LEAF(CarMake.NISSAN), ROGUE(CarMake.NISSAN),
	MURANO(CarMake.NISSAN), PATHFINDER(CarMake.NISSAN), ARMADA(CarMake.NISSAN), FRONTIER(CarMake.NISSAN),
	TITAN(CarMake.NISSAN), GT_R(CarMake.NISSAN), ONE_SERIES(CarMake.BMW), TWO_SERIES(CarMake.BMW),
	THREE_SERIES(CarMake.BMW), FOUR_SERIES(CarMake.BMW), FIVE_SERIES(CarMake.BMW), SIX_SERIES(CarMake.BMW),
	SEVEN_SERIES(CarMake.BMW), EIGHT_SERIES(CarMake.BMW), M2(CarMake.BMW), M3(CarMake.BMW), M4(CarMake.BMW),
	M5(CarMake.BMW), M6(CarMake.BMW), X1(CarMake.BMW), X2(CarMake.BMW), X3(CarMake.BMW), X4(CarMake.BMW),
	X5(CarMake.BMW), X6(CarMake.BMW), X7(CarMake.BMW), Z4(CarMake.BMW), I3(CarMake.BMW), I8(CarMake.BMW),
	A_CLASS(CarMake.MERCEDES_BENZ), B_CLASS(CarMake.MERCEDES_BENZ), C_CLASS(CarMake.MERCEDES_BENZ),
	E_CLASS(CarMake.MERCEDES_BENZ), S_CLASS(CarMake.MERCEDES_BENZ), G_CLASS(CarMake.MERCEDES_BENZ),
	GLA_CLASS(CarMake.MERCEDES_BENZ), GLC_CLASS(CarMake.MERCEDES_BENZ), GLE_CLASS(CarMake.MERCEDES_BENZ),
	GLS_CLASS(CarMake.MERCEDES_BENZ), CLA_CLASS(CarMake.MERCEDES_BENZ), CLS_CLASS(CarMake.MERCEDES_BENZ),
	SL_CLASS(CarMake.MERCEDES_BENZ), SLC_CLASS(CarMake.MERCEDES_BENZ), AMG_GT(CarMake.MERCEDES_BENZ),
	EQS(CarMake.MERCEDES_BENZ), A1(CarMake.AUDI), A3(CarMake.AUDI), A4(CarMake.AUDI), A5(CarMake.AUDI),
	A6(CarMake.AUDI), A7(CarMake.AUDI), A8(CarMake.AUDI), Q2(CarMake.AUDI), Q3(CarMake.AUDI), Q4(CarMake.AUDI),
	Q5(CarMake.AUDI), Q6(CarMake.AUDI), Q7(CarMake.AUDI), Q8(CarMake.AUDI), TT(CarMake.AUDI), R8(CarMake.AUDI),
	E_TRON(CarMake.AUDI), BEETLE(CarMake.VOLKSWAGEN), GOLF(CarMake.VOLKSWAGEN), JETTA(CarMake.VOLKSWAGEN),
	PASSAT(CarMake.VOLKSWAGEN), POLO(CarMake.VOLKSWAGEN), TIGUAN(CarMake.VOLKSWAGEN), TOUAREG(CarMake.VOLKSWAGEN),
	ARTEON(CarMake.VOLKSWAGEN), ATLAS(CarMake.VOLKSWAGEN), CC(CarMake.VOLKSWAGEN), EOS(CarMake.VOLKSWAGEN),
	GTI(CarMake.VOLKSWAGEN), SCIROCCO(CarMake.VOLKSWAGEN), THING(CarMake.VOLKSWAGEN), TOUAREG_2(CarMake.VOLKSWAGEN),
	TOUAREG_3(CarMake.VOLKSWAGEN), TOUAREG_TDI(CarMake.VOLKSWAGEN), UP(CarMake.VOLKSWAGEN), ACCENT(CarMake.HYUNDAI),
	ELANTRA(CarMake.HYUNDAI), SONATA(CarMake.HYUNDAI), AZERA(CarMake.HYUNDAI), VELOSTER(CarMake.HYUNDAI),
	KONA(CarMake.HYUNDAI), TUCSON(CarMake.HYUNDAI), SANTA_FE(CarMake.HYUNDAI), PALISADE(CarMake.HYUNDAI),
	IONIQ(CarMake.HYUNDAI), NEXO(CarMake.HYUNDAI), GENESIS_G70(CarMake.HYUNDAI), GENESIS_G80(CarMake.HYUNDAI),
	GENESIS_G90(CarMake.HYUNDAI);

	private final CarMake make;

	CarModel(CarMake make) {
		this.make = make;
	}

	public CarMake getMake() {
		return make;
	}
}
