package ca.sheridancollege.billana.domain;

public enum ServiceLabels {

	VACCUM_INTERIOR,
	WASH_RUBBER_FLOOR_MATS,
	DETAIL_INTERIOR,
	CLEAN_WINDOWS,
	CLEAN_DOOR_JAMBS,
	AIR_FRESHNER,
	WASH_EXTERIOR,
	DRESS_TIRES,
	CLEAN_WHEELS,
	CHAMOIS_DRY,
	SHAMPOO_CARPETS,
	SHAMPOO_SEATS,
	APPLY_ONE_COAT_OF_WAX,
	APPLY_THREE_COATS_OF_WAX,
	BUFFING_AND_COMPOUNDING
	
}
